/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Estructuras.Documento;
import Estructuras.ListaSimpleDocumentos;
import Estructuras.ListaSimpleUsuarios;
import Estructuras.NodoSimple;
import Estructuras.Usuario;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana Blanco
 */
public class BasedeDatos_interfaz extends javax.swing.JFrame {
    
    DefaultTableModel tabla = new DefaultTableModel();
    public static Global global;
    private int filas;

    /**
     * Creates new form BasedeDatos_interfaz
     */
    public BasedeDatos_interfaz(Global global) {
        this.filas= 0;
        this.global = global;
        initComponents();
        this.setLocationRelativeTo(null);
        NodoSimple aux = global.getListaUsuarios().getpFirst();
        for (int i = 0; i < global.getListaUsuarios().getSize(); i++) {
            Usuario usuario = (Usuario) aux.getData();
            ComboBoxUsuarios.addItem(usuario.getName().toString());
            aux = aux.getPnext();
        }
        
        String[] titulos= {"Título","Tipo", "Páginas", "Mandado a imprimir"};
        tabla.setColumnIdentifiers(titulos);
        tabla1.setModel(tabla);
    }
    
    
    public void borrar(){
    
        int contador = 0;
        int variable =0;
        
        while(this.filas != 0 && this.filas !=contador){
            tabla.removeRow(variable);
            contador ++;
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        ComboBoxUsuarios = new javax.swing.JComboBox<>();
        selected = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Back.setText("Regresar");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título", "Tipo", "Páginas", "Mandado a imprimir"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 410, 330));

        getContentPane().add(ComboBoxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 146, -1));

        selected.setText("Seleccionar");
        selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedActionPerformed(evt);
            }
        });
        getContentPane().add(selected, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, -1));

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        
        /**
         * Método que abre la interfaz principal
         * Realizado por: Ana Blanco.
         * Versión: 11/25/2023
         */
        start_interfaz back = new start_interfaz(this.global);
        this.setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void selectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedActionPerformed
        /**
         * Método que se encarga de mostrar los datos de los usuarios y todos los documentos 
         * que tiene el usuario creados.
         * Realizado por: Ana Blanco.
         * Versión: 11/25/2023
         */
        this.borrar();
        String info ="";
        
        String usuario = (String) ComboBoxUsuarios.getSelectedItem();
        int num = this.global.getHashtable().hash(usuario);
        ListaSimpleUsuarios usuarios = this.global.getHashtable().getTable()[num];
        NodoSimple aux = usuarios.getpFirst();
        for (int i = 0; i < usuarios.getSize(); i++) {
            Usuario user = (Usuario) aux.getData();
            boolean entra = true;
            if (user.getName().equalsIgnoreCase(usuario)) {
                info += "Nombre: "+user.getName()+"\n"+"Tipo: "+ user.getPrioridad();
                TextArea.setText(info);
                ListaSimpleDocumentos docs = user.getDocs();
                if (docs.EsVacia()) {
                    JOptionPane.showMessageDialog(null, "Este usuario no tiene documentos");
                } else {
                    NodoSimple doc =docs.getpFirst();
                    for (int j = 0; j < docs.getSize(); j++) {
                        Documento docu = (Documento)doc.getData();
                        tabla.addRow(new Object[]{docu.getTitulo(), docu.getTipo(),docu.getTamaño(), docu.isEncola()});
                        doc = doc.getPnext();
                    
                    }
              
                }
                this.filas = docs.getSize();
                break;
                
            } else if(entra){
                aux = aux.getPnext();
            }
        }
    }//GEN-LAST:event_selectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasedeDatos_interfaz(global).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> ComboBoxUsuarios;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton selected;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
