/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Estructuras.Documento;
import Estructuras.ListaSimpleUsuarios;
import Estructuras.NodoSimple;
import Estructuras.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Blanco
 */
public class CrearDocumento extends javax.swing.JFrame {

    public static Global global;

    /**
     * Creates new form CrearDocumento
     */
    public CrearDocumento(Global global) {
        this.global = global;
        initComponents();
        this.setLocationRelativeTo(null);
        NodoSimple aux = global.getListaUsuarios().getpFirst();
        for (int i = 0; i < global.getListaUsuarios().getSize(); i++) {
            Usuario usuario = (Usuario) aux.getData();
            ComboBox.addItem(usuario.getName().toString());
            aux = aux.getPnext();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        Titulo = new javax.swing.JTextField();
        num = new javax.swing.JSpinner();
        Crear = new javax.swing.JButton();
        Tipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Back.setText("Regresar");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 18, -1, -1));

        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, -1));
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 230, 40));
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, -1));

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        getContentPane().add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 100, 30));

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "PNG", "TXT", "CSV" }));
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        
        /**
         * Método que se encarga de crear los objetos documentos e ingresarlo a la lista de documentos
         * del usuario correspondiente
         * Realizado por: Ana Blanco.
         * Versión: 11/25/2023
         */
        
        String name = " ";
        String tipo = "";
        name += Titulo.getText().trim();
        int tamano = (int) num.getValue();

        if (!name.equals(" ") && tamano > 0) {
            name = name.trim();
            tipo += Tipo.getSelectedItem();
            Documento nuevo = new Documento(name, tamano, tipo);

            String usuario = ComboBox.getSelectedItem().toString();

            int indice = this.global.getHashtable().hash(usuario);

            ListaSimpleUsuarios lista = this.global.getHashtable().getTable()[indice];
            NodoSimple aux = lista.getpFirst();
            Usuario data = (Usuario) aux.getData();

            for (int i = 0; i < lista.getSize(); i++) {
                if (data.getName().equalsIgnoreCase(usuario)) {
                    if (!this.global.getListaUsuarios().buscarDocumento(name)) {
                        data.getDocs().addend(nuevo);
                        JOptionPane.showMessageDialog(null, "El documento se ha creado exitosamente");
                        break;
                    }else{
                        JOptionPane.showMessageDialog(null, "El nombre del documento no está disponible");
                        break;
                    }
                } else {
                    aux = aux.getPnext();
                    data = (Usuario) aux.getData();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos de título y la cantidad de páginas mayor que cero");
        }

    }//GEN-LAST:event_CrearActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        /**
         * Método que abre la interfaz principal
         * Realizado por: Ana Blanco.
         * Versión: 11/25/2023
         */
        
        this.setVisible(false);
        Documentos_interfaz v2 = new Documentos_interfaz(this.global);
        v2.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearDocumento(global).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Crear;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner num;
    // End of variables declaration//GEN-END:variables
}
