/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Estructuras.NodoSimple;
import Estructuras.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Blanco
 */
public class EliminarUsuarios extends javax.swing.JFrame {
    
    static public Global global;
    /**
     * Creates new form EliminarUsuarios
     */
    public EliminarUsuarios(Global global) {
        this.global = global;
        initComponents();
        this.setLocationRelativeTo(null);
        NodoSimple aux = global.getListaUsuarios().getpFirst();
        for (int i = 0; i < global.getListaUsuarios().getSize(); i++) {
            Usuario usuario = (Usuario) aux.getData();
            ComboBox.addItem(usuario.getName().toString());
            aux = aux.getPnext();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Back.setText("Regresar");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 12, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 100, -1));

        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
         /**
         * Método que abre la interfaz principal
         * Realizado por: Ana Blanco.
         * Versión: 11/25/2023
         */
        
        this.setVisible(false);
        Usuarios_interfaz v2 = new Usuarios_interfaz(this.global);
        v2.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        /**
         * Método que elimina los usuarios en la lista de usuarios y en el hashtable
         * Realizado por: Ana Blanco.
         * Versión: 11/25/2023
         */
        
        String usuario = ComboBox.getSelectedItem().toString();
        
//      Aquí se elimina el usuario de la lista        
        this.global.getListaUsuarios().EliminarPorReferencia(usuario);
        
       
//      Acá se elimina del  hashtable
        int hash = this.global.getHashtable().hash(usuario);
        this.global.getHashtable().delete_usuario(hash, usuario);
        
        JOptionPane.showMessageDialog(null, "El usuario: " + ComboBox.getSelectedItem().toString() + ", fué eliminado");

//      Volvemos a llenar el combobox, sin el usuario que se eliminó
        NodoSimple aux = this.global.getListaUsuarios().getpFirst();
        ComboBox.removeAllItems();
        for (int i = 0; i < this.global.getListaUsuarios().getSize(); i++) {
            Usuario usuario1 = (Usuario)aux.getData();
            ComboBox.addItem(usuario1.getName());
            aux = aux.getPnext();
        }
        
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarUsuarios(global).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
