/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Estructuras.Usuario;
import Funciones.funciones;
import com.sun.tools.javac.Main;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ana Blanco
 */
public class start_interfaz extends javax.swing.JFrame {

    /**
     * Creates new form start_interfaz
     */
    private String path;

    public start_interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.path = null;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarUsuariosButton = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        Documentos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Impresora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CargarUsuariosButton.setText("Cargar Usuarios");
        CargarUsuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarUsuariosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CargarUsuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 370, 30));

        Usuarios.setText("Manejo de usuarios");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 370, 30));

        Documentos.setText("Manejo de documentos");
        Documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentosActionPerformed(evt);
            }
        });
        getContentPane().add(Documentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 370, 30));

        jButton1.setText("Guardar información");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 370, 30));

        Impresora.setText("Manejo de impresora");
        Impresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpresoraActionPerformed(evt);
            }
        });
        getContentPane().add(Impresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 370, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarUsuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarUsuariosButtonActionPerformed

        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv", "csv");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        file.setFileFilter(filter);
        int selection = file.showOpenDialog(this);

        if (selection == JFileChooser.APPROVE_OPTION) {

            File archive = file.getSelectedFile();
            String path = archive.getAbsolutePath();
            setPath(path);
            if (!path.contains("csv")) {
                JOptionPane.showMessageDialog(null, "Por favor elija un archivo del tipo csv");
            } else {
                try {
                    File archivo = new File(path);
                    FileReader fr = new FileReader(archivo);
                    BufferedReader br = new BufferedReader(fr);

                    String usuarios;
                    String UsuariosInfo = "";

                    while ((usuarios = br.readLine()) != null) {

                        if (!usuarios.isEmpty() && !usuarios.isBlank()) {
                            UsuariosInfo += usuarios + "\n";

                        }
                    }
                    fr.close();
                    br.close();
                    UsuariosInfo = UsuariosInfo.trim();

                    if (!"".equals(UsuariosInfo)) {

                        String[] info1 = UsuariosInfo.split("\n");

                        for (int i = 1; i < info1.length; i++) {
                            String[] info2 = info1[i].split(",");
                            Usuario usuario = new Usuario(info2[0], info2[1]);
                            Global.getListaUsuarios().addend(usuario);
                            int hash = Global.getHashtable().hash(usuario.getName());
                            Global.getHashtable().Insert_Usuario(hash, usuario);
                        }

                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error!!!");

                }
            }
        }
    }//GEN-LAST:event_CargarUsuariosButtonActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        this.setVisible(false);
        Usuarios_interfaz v2 = new Usuarios_interfaz();
        v2.setVisible(true);
        
    }//GEN-LAST:event_UsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String todo = Global.getListaUsuarios().getAllUsers();

        try {
            if (getPath() != null) {
                PrintWriter pw = new PrintWriter(getPath());
                pw.print(todo);
                pw.close();
                JOptionPane.showMessageDialog(null, "Guardado exitoso");
            } else {
                JOptionPane.showMessageDialog(null, "Error!! Primero debe cargar un archivo txt");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!!!!!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpresoraActionPerformed
        this.setVisible(false);
        Impresora_interfaz v2 = new Impresora_interfaz();
        v2.setVisible(true);
    }//GEN-LAST:event_ImpresoraActionPerformed

    private void DocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentosActionPerformed
        this.setVisible(false);
        Documentos_interfaz v2 = new Documentos_interfaz();
        v2.setVisible(true);
    }//GEN-LAST:event_DocumentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarUsuariosButton;
    private javax.swing.JButton Documentos;
    private javax.swing.JButton Impresora;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
